on:
  push:
    branches: [ "develop" ]

jobs:
  notify-merge:
    if: github.event_name == 'push'  # Solo en pushes (merges) a develop
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Merge
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'Merge exitoso a develop! Commit: {{ EVENT_PAYLOAD.head_commit.message }} por {{ EVENT_PAYLOAD.pusher.name }}'